### ISSUE TITLE
Hand of the Gods Endpoint

### ISSUE THREAD

**Issue by stachu540** [stachu540/HiRezAPI#15]
### ***Planned***

Feature has been planed. More information is unknown.

**Comment by T0miii** [comment]
Hello,

 how is it going with the Hand of the Gods API.
Would love to create a deck building site, but could not finde any API, and HIREZ wont answer the Emails about official API. :)

**Comment by stachu540** [comment]
Information is pending. All devs doesn't know when will be.

**Comment by T0miii** [comment]
Okay, thx for the Info. :+1:
