### ISSUE TITLE
README maven import issues

### ISSUE THREAD

**Issue by CustardGod** [stachu540/HiRezAPI#54]
**Describe the bug**
On the README the maven import is:
```
<dependencies>
    <dependency>
          <groupId>com.github.stachu540</groupId>
          <!--for all games-->
          <artifactId>HiRezAPI-core</artifactId> 
          <!--for paladins-->
          <!--<artifactId>HiRezAPI-paladins</artifactId>-->
          <!--for smite-->
          <!--<artifactId>HiRezAPI-smite</artifactId>-->
          <version>2.1.0</version>
     </dependency>
</dependencies>
```
The artifact IDs should be `Api` not `API`
This cause an issue where even if corrected to the lower case version it would not import until the `API` files were deleted from the local machine

**To Reproduce**
1. Import using capital `API`
2. Attempt to use lower case `Api`

**Expected behavior**
Import should work as expected

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IntelliJ 2017.3.5

**Comment by stachu540** [comment]
Readme has been updated. Thank you!
