### ISSUE TITLE
Expose more fields

### ISSUE THREAD

**Issue by CristianSarac** [stachu540/HiRezAPI#55]
Is it possible to expose the fields lore,name, from the God class? 
 Currently the God class has a lot of info but it is not  related to any specific God.

**Comment by stachu540** [comment]
This should be done in next release. I can say it is planned to rewrite into Kotlin, but it will be support JVM too, swiftly, :)

**Comment by CristianSarac** [comment]
Awesome, looking forward to the next release

**Comment by stachu540** [comment]
Relating to #56 

https://pastebin.com/PM1uXxH5
https://pastebin.com/jn6tvbMY

It should be satisfied?

**Comment by CristianSarac** [comment]
Yeah i think that will do

**Comment by stachu540** [comment]
We going home to v3.
TL;DR Kotlin is bad for creating some static methods.
Soo I've decided to stay into Java. More info soon... :tm:
