### ISSUE TITLE
How can i create a session?

### ISSUE THREAD

**Issue by Slenderman0039** [stachu540/HiRezAPI#90]
Hi , i think you developed a great project and i want to use it for my personal use, but i have a problem : ‘hirez.api.HiRezException: Require generate session for: createsession’
How can i solve this ? 

I have to create a new session but i don’t understand how i can create it... 

Thank you so much

**Comment by stachu540** [comment]
Session should be create automatically. If will not create it, try use `createSession().subscribe()`, Then try call some other methods.

PS. Apologize for further delay.

**Comment by shinixsensei-dev** [comment]
I am getting a NullPointerException when using this Method.

```java
ConfigurationBuilder configurationBuilder = new ConfigurationBuilder();
                    configurationBuilder.setAuthKey(Config.AUTH_KEY);
                    configurationBuilder.setDevId(Config.DEV_ID);
                    configurationBuilder.build();
                    Paladins.createSession().subscribe();

                    Paladins.initConfig(configurationBuilder);



                    Paladins.getMatchDetails(c.getMatchID());
```

**Comment by stachu540** [comment]
Reference to #92
