### ISSUE TITLE
Cannot resolve com.github.stachu540.HiRezAPI:HiRezAPI-all:v3.0.0

### ISSUE THREAD

**Issue by crnvl** [stachu540/HiRezAPI#91]
**Describe the bug**
I tried to use the Maven Dependency for this Repo, but I am unable to install it, 
It's always giving me a different Error Message depending on from where i get the dependency (jitpack, jcenter, ...).
I successfully imported it a few times, but i wasn't able to use the Examples from the Wiki then.

**To Reproduce**
1. Use Dependency from README
2. Install
3. See error

**Expected behavior**
Proper Installation ig?

**Desktop (please complete the following information):**
 - OS: Win 10
 - JDK 11

**Comment by stachu540** [comment]
related to [#89](https://github.com/stachu540/HiRezAPI/issues/89#issuecomment-566646882)

**Comment by crnvl** [comment]
I already tried using that dependency, but it's still not working

**Comment by stachu540** [comment]
it is `3.0.0` not `v3.0.0`
![image](https://user-images.githubusercontent.com/359222/84793504-7996dd80-aff5-11ea-928b-218cee1ca9b3.png)

**Comment by crnvl** [comment]
I thought, I'd have tried to import it without the ``v`` already, but it has been imported now, thanks for the fast response!
