### ISSUE TITLE
Cannot create Session

### ISSUE THREAD

**Issue by crnvl** [stachu540/HiRezAPI#92]
**Describe the bug**
My Code is 
```java
ConfigurationBuilder configurationBuilder = new ConfigurationBuilder();
                    configurationBuilder.setAuthKey(Config.AUTH_KEY);
                    configurationBuilder.setDevId(Config.DEV_ID);
                    configurationBuilder.build();

                    Paladins.initConfig(configurationBuilder);

                    Flowable<MatchDetail> matchDetails = Paladins.getMatchDetails(c.getMatchID());
                    Flowable<PlayerLoadout> playerLoadoutFlowable = Paladins.getPlayerLoadouts(args[0]);
```
But I always get Errors like 
```hirez.api.HiRezException: Require generate session for: testsession```.

I already tried using 
```java
CreateSession session = new CreateSession();
```
but it doesn't seem to fix anything.
Idk, I heard it's supposed to create them automatically, but that also doesn't work for me somehow.

**Desktop (please complete the following information):**
 - Win 10
 - JDK 11

**Comment by stachu540** [comment]
ref: [#90](https://github.com/stachu540/HiRezAPI/issues/90#issuecomment-644836456)

**Comment by crnvl** [comment]
Yep, I tried that, but I may not know how to use it correctly, because i can't get it to work properly.

**Comment by crnvl** [comment]
If I use ``Paladins.createSession().subscribe();`` before every other Command related to the API it returns a NullPointerException

**Comment by stachu540** [comment]
Fix probably will be in `3.1.0` with Dependency updates and small API changes

**Comment by crnvl** [comment]
Thanks a lot!

**Comment by stachu540** [comment]
If you try play with [jitpack](https://jitpack.io/#stachu540/HiRezAPI/master-SNAPSHOT) and confirm, the issue has been fixed? I will release new version on Friday.

Also there is changes so.. there is NO static methods, they are in the class after initializing them, using `create()` static method. This method are consumer so it is simplified to build configuration, inside the `Consumer`. Also i've add 2 properties to builder which can helps to deliver your own parameters for `ObjectMapper` and `OkHttpClient.Builder`.

**Comment by stachu540** [comment]
The bug should be fixed, in the next release
